- index.js
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Remove Opening Message
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #11 
| How to test?  | N/A
> Remove Opening Message

- config.js
- src/pull-request-data-provider.js
- src/rules/E3.js
| Description?      | Change kanban names
| How to test?      | Issue bot re-start to do his job again
| Possible impacts? | -
> Change kanban names

- config.js
| Description?      | Change kanban names for 1.7.7.4
| How to test?      | Issuebot must work
| Possible impacts? | -
> Change kanban names for 1.7.7.4

- config.js
| Description?      | Change kanban names for 1.7.7.5
| How to test?      | Issuebot must act on 1.7.7.5 issues
| Possible impacts? | -
> Change kanban names for 1.7.7.5

- config.js
| Description?      | Update config to remove 1.7.7.5 and add 1.7.7.6
| Type?             | improvement
| BC breaks?        | yes
| Deprecations?     | yes
| How to test?      | -
> Update config for kanban 1.7.7.6

- .env.example
- src/pull-request-data-provider.js
| Description?      | Installation ID is the ID of the app in your project
| Type?             | improvement
| How to test?      | -
| Possible impacts? | Need to modify install script on prod env
> Make InstallationId configurable

- config.js
| Description?      | Add 1.7.8.3 kanban 
| Type?             | improvement
| Fixed ticket?     | no issue
| How to test?      | 1.7.8.3 kanban should behave like 1.7.8.1 and 8.0.0 kanbans
| Possible impacts? |
> take kanban 1.7.8.3 into account

- config.js
| Description?      | Add new 1.7.8.4 kanban
| Type?             | improvement
| Fixed ticket?     | none
| How to test?      | 
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
> add 1.7.8.4 kanban

- config.js
- src/config-provider.js
- src/issue-comments-data-provider.js
- src/maxikanban/changeColumn.js
- src/maxikanban/createCard.js
- src/maxikanban/deleteCard.js
- src/maxikanban/getIssue.js
- src/maxikanban/getProjectFieldDatas.js
- src/rule-computer.js
- src/ruleFinder/IssueCommentsRuleFinder.js
- src/ruleFinder/IssueRuleFinder.js
- src/ruleFinder/ProjectCardRuleFinder.js
- src/rules/C2.js
- src/rules/C3.js
- src/rules/D2.js
- src/rules/D4.js
- src/rules/E3.js
- src/rules/E4.js
- src/rules/E5.js
- src/rules/F1.js
- src/rules/G2.js
- src/rules/H2.js
- src/rules/I1.js
- src/rules/J1.js
- src/rules/J4.js
- src/rules/L1.js
- src/rules/L2.js
- src/rules/L3.js
- src/rules/Rule.js
Reverts PrestaShop/issuebot#50
> Revert of the revert

- config.js
- src/config-provider.js
- src/issue-comments-data-provider.js
- src/maxikanban/changeColumn.js
- src/maxikanban/createCard.js
- src/maxikanban/deleteCard.js
- src/maxikanban/getIssue.js
- src/maxikanban/getProjectFieldDatas.js
- src/rule-computer.js
- src/ruleFinder/IssueCommentsRuleFinder.js
- src/ruleFinder/IssueRuleFinder.js
- src/ruleFinder/ProjectCardRuleFinder.js
- src/rules/C2.js
- src/rules/C3.js
- src/rules/D2.js
- src/rules/D4.js
- src/rules/E3.js
- src/rules/E4.js
- src/rules/E5.js
- src/rules/F1.js
- src/rules/G2.js
- src/rules/H2.js
- src/rules/I1.js
- src/rules/J1.js
- src/rules/J4.js
- src/rules/L1.js
- src/rules/L2.js
- src/rules/L3.js
- src/rules/Rule.js
Reverts PrestaShop/issuebot#52
> Add MegaKanban again

- src/maxikanban/getProjectFieldDatas.js
> fix: optional chaining not supported in production

- src/maxikanban/getProjectFieldDatas.js
Reverts PrestaShop/issuebot#54
> Revert "fix: optional chaining not supported in production"

- config.js
- src/config-provider.js
- src/issue-comments-data-provider.js
- src/maxikanban/changeColumn.js
- src/maxikanban/createCard.js
- src/maxikanban/deleteCard.js
- src/maxikanban/getIssue.js
- src/maxikanban/getProjectFieldDatas.js
- src/rule-computer.js
- src/ruleFinder/IssueCommentsRuleFinder.js
- src/ruleFinder/IssueRuleFinder.js
- src/ruleFinder/ProjectCardRuleFinder.js
- src/rules/C2.js
- src/rules/C3.js
- src/rules/D2.js
- src/rules/D4.js
- src/rules/E3.js
- src/rules/E4.js
- src/rules/E5.js
- src/rules/F1.js
- src/rules/G2.js
- src/rules/H2.js
- src/rules/I1.js
- src/rules/J1.js
- src/rules/J4.js
- src/rules/L1.js
- src/rules/L2.js
- src/rules/L3.js
- src/rules/Rule.js
Reverts PrestaShop/issuebot#56
> Add megakanban features

- config.js
> feat: add 1.7.8.5 kanban

- src/maxikanban/getProjectFieldDatas.js
> fix: debug log for production env

- src/maxikanban/getProjectFieldDatas.js
> fix: avoid issuebot crash if fieldValues is unreachable

- src/rule-applier.js
- src/rule.js
- src/ruleFinder/IssueCommentsRuleFinder.js
- src/rules/M2.js
| Description?      | This PR adds a new scenario: when an issue receives a new comment, whoever wrote it, the label `waiting for authors` is removed (if it exists)
| Type?             | new feature
| Fixed ticket?     | Fixes #47
| How to test?      | See issue #47
| Possible impacts? | --
> Add new M2 rule

- src/maxikanban/changeColumn.js
- src/maxikanban/getProjectFieldDatas.js
> fix: some errors because of multiple graphql calls

- config.js
> fix: remove empty character on waiting for author

- src/ruleFinder/PullRequestRuleFinder.js
> fix: debug nbReview in production

- src/pull-request-data-provider.js
> fix: debug reviews call

- src/pull-request-data-provider.js
- src/ruleFinder/PullRequestRuleFinder.js
> fix: nbCount review bug

- src/pull-request-data-provider.js
> fix: debug log for the Fixed label

- config.js
- src/issue-comments-data-provider.js
| Description?      | we should check that the same author is not counted twice or more
| Fixed ticket?     | 
| How to test?      | 
| Possible impacts? |
> Fix count authors for top watcher label applyance

- src/issue-data-provider.js
- src/pull-request-data-provider.js
- src/rule-applier.js
- src/rule-computer.js
- src/rule.js
- src/ruleFinder/ProjectCardRuleFinder.js
- src/rules/Rule.js
- src/services/changeColumn.js
- src/services/createCard.js
- src/services/deleteCard.js
- src/services/getIssue.js
- src/services/getProjectFieldDatas.js
- src/services/getStatus.js
| Description?      | As github added maxikanban events, we need to handle them, and the API is deprecated so we need to migrate to the new one
| Type?             | new feature
> Update to new API and manage maxikanban cards events

- config.js
> Add new kanbans

- src/issue-comments-data-provider.js
- src/ruleFinder/IssueCommentsRuleFinder.js
- src/ruleFinder/ProjectCardRuleFinder.js
- src/rules/M1.js
- src/rules/M2.js
| Description?      | Don't add Topwatcher label to closed issues (and fix linter issues)
| Fixed ticket?     | Fixes #78
> Don't add Topwatcher label to closed issues

- index.js
- src/ruleFinder/IssueCommentsRuleFinder.js
- src/ruleFinder/ProjectCardRuleFinder.js
- tests/config.js
- tests/move-issue-to-kanban-from-status.test.js
- tests/payload/comment/created.json
- tests/remove-waiting-for-author-on-comment.test.js
- tests/test-utils.js
| Description?      | Fix removing `Waiting for author` label behaviour with this new condition: <br/>- Issue with at least `Waiting for author`.<br/>- Comment posted by the issue author.
| Fixed ticket?     | Fixes #102, Fixes #91
| Sponsor company   | 
| How to test?      |
> Fix removing `Waiting for author` label behaviour

- .github/workflows/production-workflow.yml
Production workflow draft
| Description?      | Production workflow that will be trigger with release creation
| Type?             | new feature
| How to test?      | We need to create a release to test the workflow
> Feat: Production deployment
